/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Resources.EducationResource;
import Business.Resources.FoodResource;
import Business.Resources.HealthResource;
import Business.Resources.MoneyResource;
import Business.UserAccount.UserAccount;
import Business.Utility.EmailUtility;
import Business.WorkQueue.ResourcesWorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import java.util.List;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shukl
 */
public class RequestResourceJPanel extends JPanel {

    private EcoSystem system;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount account;
     private EmailUtility emailUtility;

    /**
     * Creates new form RaiseCsrActivityJPanel
     */
    public RequestResourceJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.enterprise = enterprise;
        requestIdTextField.setText(String.valueOf(EcoSystem.counter++));
        fillLocalityComboField();
        this.account = account;
        numberOfDoctorTextField.setEnabled(false);
        nameOfMedicineTextField.setEnabled(false);
        quantityOfMedicineTextField.setEnabled(false);
        numberOfEducationSuppliesTextField.setEnabled(false);
        numberOfPacketsTestField.setEnabled(false);
        numberOfTeacherTextField.setEnabled(false);
        moneyTextField.setEnabled(false);
        typeOfMedicineTextField.setEnabled(false);
    }

    public void fillLocalityComboField() {
        localityComboField.removeAllItems();

        for (Network network : system.getNetworkList()) {
            localityComboField.addItem(network);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        requestIdTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descriptionTextField = new javax.swing.JTextArea();
        requestTypeComboField = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        localityComboField = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        resourceList = new javax.swing.JList();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        numberOfEducationSuppliesTextField = new javax.swing.JTextField();
        numberOfTeacherTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        numberOfPacketsTestField = new javax.swing.JTextField();
        nameOfMedicineTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        quantityOfMedicineTextField = new javax.swing.JTextField();
        typeOfMedicineTextField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        numberOfDoctorTextField = new javax.swing.JTextField();
        moneyTextField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        raiseRequestButton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonDashboard = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        requestRaiseButton = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        requestRaiseButton1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        requestIdTextField.setText(" ");

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Request ID");

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Description");

        descriptionTextField.setColumns(20);
        descriptionTextField.setRows(5);
        jScrollPane3.setViewportView(descriptionTextField);

        requestTypeComboField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Community", "Individual" }));
        requestTypeComboField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("On behalf of ");

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Locality");

        localityComboField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        localityComboField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        resourceList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Education", "Health", "Food", "Money" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        resourceList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                resourceListValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(resourceList);

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Resources Needed");

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("No of education Supplies");

        numberOfEducationSuppliesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfEducationSuppliesTextFieldjTextField2ActionPerformed(evt);
            }
        });

        numberOfTeacherTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfTeacherTextFieldjTextField3ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("No of teacher required");

        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("No of Food packets Req");

        numberOfPacketsTestField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfPacketsTestFieldjTextField4ActionPerformed(evt);
            }
        });

        nameOfMedicineTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameOfMedicineTextFieldjTextField5ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Name of medicine required");

        jLabel26.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Quantity of medicines ");

        quantityOfMedicineTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityOfMedicineTextFieldjTextField6ActionPerformed(evt);
            }
        });

        typeOfMedicineTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeOfMedicineTextFieldjTextField7ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Type of Medicine required");

        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("No of doctors required");

        numberOfDoctorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfDoctorTextFieldjTextField7ActionPerformed(evt);
            }
        });

        moneyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyTextFieldjTextField8ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Money Required in USD ");

        raiseRequestButton.setBackground(new java.awt.Color(0, 0, 0));
        raiseRequestButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        raiseRequestButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raiseRequestButtonMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RAISE A REQUEST");

        javax.swing.GroupLayout raiseRequestButtonLayout = new javax.swing.GroupLayout(raiseRequestButton);
        raiseRequestButton.setLayout(raiseRequestButtonLayout);
        raiseRequestButtonLayout.setHorizontalGroup(
            raiseRequestButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(raiseRequestButtonLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        raiseRequestButtonLayout.setVerticalGroup(
            raiseRequestButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, raiseRequestButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        backJButton.setBackground(new java.awt.Color(0, 0, 0));
        backJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        backJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backJButtonMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BACK");

        javax.swing.GroupLayout backJButtonLayout = new javax.swing.GroupLayout(backJButton);
        backJButton.setLayout(backJButtonLayout);
        backJButtonLayout.setHorizontalGroup(
            backJButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backJButtonLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        backJButtonLayout.setVerticalGroup(
            backJButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backJButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(localityComboField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(requestTypeComboField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(numberOfPacketsTestField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(numberOfTeacherTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(numberOfEducationSuppliesTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quantityOfMedicineTextField)
                                    .addComponent(typeOfMedicineTextField)
                                    .addComponent(numberOfDoctorTextField)
                                    .addComponent(moneyTextField))
                                .addGap(63, 63, 63)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(requestIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(39, 39, 39)
                        .addComponent(nameOfMedicineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(raiseRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(requestIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel17))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(requestTypeComboField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(localityComboField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(numberOfEducationSuppliesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel21)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(numberOfTeacherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(numberOfPacketsTestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(nameOfMedicineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(quantityOfMedicineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(typeOfMedicineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfDoctorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(moneyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(raiseRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 680, 790));

        jPanel4.setBackground(new java.awt.Color(22, 16, 16));

        jLabel28.setBackground(new java.awt.Color(102, 102, 102));
        jLabel28.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 204));
        jLabel28.setText("Helping");

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Hands");

        buttonDashboard.setBackground(new java.awt.Color(22, 16, 16));
        buttonDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDashboardMouseClicked(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setText("Dashboard");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pen-tablet.png"))); // NOI18N

        javax.swing.GroupLayout buttonDashboardLayout = new javax.swing.GroupLayout(buttonDashboard);
        buttonDashboard.setLayout(buttonDashboardLayout);
        buttonDashboardLayout.setHorizontalGroup(
            buttonDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonDashboardLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        buttonDashboardLayout.setVerticalGroup(
            buttonDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonDashboardLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonDashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        requestRaiseButton.setBackground(new java.awt.Color(204, 204, 204));
        requestRaiseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestRaiseButtonMouseClicked(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Raise a Request");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file-hand.png"))); // NOI18N

        javax.swing.GroupLayout requestRaiseButtonLayout = new javax.swing.GroupLayout(requestRaiseButton);
        requestRaiseButton.setLayout(requestRaiseButtonLayout);
        requestRaiseButtonLayout.setHorizontalGroup(
            requestRaiseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestRaiseButtonLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        requestRaiseButtonLayout.setVerticalGroup(
            requestRaiseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestRaiseButtonLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestRaiseButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        requestRaiseButton1.setBackground(new java.awt.Color(22, 16, 16));
        requestRaiseButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestRaiseButton1MouseClicked(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("View Raised Request");

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content-book-2.png"))); // NOI18N

        javax.swing.GroupLayout requestRaiseButton1Layout = new javax.swing.GroupLayout(requestRaiseButton1);
        requestRaiseButton1.setLayout(requestRaiseButton1Layout);
        requestRaiseButton1Layout.setHorizontalGroup(
            requestRaiseButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestRaiseButton1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        requestRaiseButton1Layout.setVerticalGroup(
            requestRaiseButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestRaiseButton1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestRaiseButton1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addComponent(buttonDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(requestRaiseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(requestRaiseButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requestRaiseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requestRaiseButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(759, Short.MAX_VALUE))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 1090));

        jLabel5.setBackground(new java.awt.Color(22, 16, 16));
        jLabel5.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(22, 16, 16));
        jLabel5.setText("USER WORK AREA");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 240, 70));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 2320, 13));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel18.setText(" to raise a request to admin.");

        jLabel35.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel35.setText("Click on \"Raise a Request\" ");

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-volunteering-filled-50.png"))); // NOI18N

        jLabel37.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel37.setText("Click on \"View requests\"  to view the");

        jLabel38.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel38.setText("previous request made.");

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-time-machine-filled-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(16, 16, 16))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(1136, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel38))
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel13))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 920, 2320, 170));
    }// </editor-fold>//GEN-END:initComponents

    private void raiseRequestButtonMouseClicked(java.awt.event.MouseEvent evt) {
      
        
       if(descriptionTextField.getText().equals(""))
       {JOptionPane.showMessageDialog(null,"Description cannot be null");
       return;
       }
        ResourcesWorkRequest workRequest = new ResourcesWorkRequest();
        workRequest.setRequsetId(Integer.parseInt(requestIdTextField.getText()));
        workRequest.setRequestDescription(descriptionTextField.getText());
        workRequest.setMessage(requestTypeComboField.getSelectedItem().toString());
        workRequest.setNetwork(localityComboField.getSelectedItem().toString());
        workRequest.setRequestDate(new Date());
        workRequest.setRaisedByAccount(account);
        workRequest.setStatus("Pending");
        //workRequest.setRaisedByAccount(account);
        List<String> selectedResources = resourceList.getSelectedValuesList();
        for (String x : selectedResources) {
            if (x.equalsIgnoreCase("Education")) 
           
            { 
                if(numberOfEducationSuppliesTextField.getText().equals("")||numberOfTeacherTextField.getText().equals(""))
                {JOptionPane.showMessageDialog(null,"Number of Teachers and Number of Education Supplies cannot be blank");
                return;}
                
                
                EducationResource resource = new EducationResource(Integer.parseInt(numberOfEducationSuppliesTextField.getText()), Integer.parseInt(numberOfTeacherTextField.getText()), "Education", EcoSystem.counter++);
                workRequest.getResourceRequested().add(resource);
                workRequest.getResourcesPendingMap().put("Education", Integer.parseInt(numberOfEducationSuppliesTextField.getText()));
            }
            if (x.equalsIgnoreCase("Food")) {
                 if(numberOfPacketsTestField.getText().equals(""))
                {JOptionPane.showMessageDialog(null,"Number of Packets cannot be null");
                return;}
               
                
                FoodResource resource = new FoodResource(Integer.parseInt(numberOfPacketsTestField.getText()), "Food", EcoSystem.counter++);
                workRequest.getResourceRequested().add(resource);
                workRequest.getResourcesPendingMap().put("Food", Integer.parseInt(numberOfPacketsTestField.getText()));
            }
            if (x.equalsIgnoreCase("Health")) {
                if(nameOfMedicineTextField.getText().equals("")||typeOfMedicineTextField.getText().equals("")||numberOfDoctorTextField.getText().equals(""))
                {JOptionPane.showMessageDialog(null,"Name of medicine , Type of medicine and Quantity of medicine cannot be blank");
                return;}
               
                
                HealthResource resource = new HealthResource(nameOfMedicineTextField.getText(), typeOfMedicineTextField.getText(), Integer.parseInt(quantityOfMedicineTextField.getText()), Integer.parseInt(numberOfDoctorTextField.getText()), "Health", EcoSystem.counter++);
                workRequest.getResourceRequested().add(resource);
                workRequest.getResourcesPendingMap().put("Health", Integer.parseInt(quantityOfMedicineTextField.getText()));

            }
            if (x.equalsIgnoreCase("Money")) {
                if(moneyTextField.getText().equals(""))
                {JOptionPane.showMessageDialog(null,"Money Requird field cannot be blank");
                return;}
               
                
                MoneyResource resource = new MoneyResource(Integer.parseInt(moneyTextField.getText()), "USD", "Money", EcoSystem.counter++);
                workRequest.getResourceRequested().add(resource);
                workRequest.getResourcesPendingMap().put("Money", Integer.parseInt(moneyTextField.getText()));

            }

            //system.getWorkQueue().getWorkRequestList().add(workRequest);
        }
        for (Network network : system.getNetworkList()) {
            if (network.getName().equalsIgnoreCase(localityComboField.getSelectedItem().toString())) {
                network.getWorkQueue().getWorkRequestList().add(workRequest);
            }
        }
         try {
              emailUtility.subject("Hello: Request Received").to(system.getCurrentUserAccount().getUsername()).cc("helping.hands.5100@gmail.com").text("Request has been raised succesfully.Please note your Request ID"+requestIdTextField.getText()+"We are working on your request, will get back to you as soon as possible.If any query mail us on helping.hands.5100@gmail.com. Thank you.").send();
              
              } catch (MessagingException ex) {
                        System.err.println(ex);
              }
        JOptionPane.showMessageDialog(null, "Request has been raised succesfully.Check you mail for details");
        descriptionTextField.setText("");
        resourceList.clearSelection();
        numberOfEducationSuppliesTextField.setText("");
        numberOfTeacherTextField.setText("");
        numberOfPacketsTestField.setText("");
        nameOfMedicineTextField.setText("");
        quantityOfMedicineTextField.setText("");
        typeOfMedicineTextField.setText("");
        numberOfDoctorTextField.setText("");
        moneyTextField.setText("");
       
    }

    private void raiseRequestButtonjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raiseRequestButtonjButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raiseRequestButtonjButton1ActionPerformed


    private void numberOfTeacherTextFieldjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfTeacherTextFieldjTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfTeacherTextFieldjTextField3ActionPerformed

    private void numberOfEducationSuppliesTextFieldjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfEducationSuppliesTextFieldjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfEducationSuppliesTextFieldjTextField2ActionPerformed

    private void numberOfPacketsTestFieldjTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfPacketsTestFieldjTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfPacketsTestFieldjTextField4ActionPerformed

    private void quantityOfMedicineTextFieldjTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityOfMedicineTextFieldjTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityOfMedicineTextFieldjTextField6ActionPerformed

    private void numberOfDoctorTextFieldjTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfDoctorTextFieldjTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfDoctorTextFieldjTextField7ActionPerformed

    private void moneyTextFieldjTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyTextFieldjTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyTextFieldjTextField8ActionPerformed

    private void nameOfMedicineTextFieldjTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameOfMedicineTextFieldjTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameOfMedicineTextFieldjTextField5ActionPerformed

    private void typeOfMedicineTextFieldjTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeOfMedicineTextFieldjTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeOfMedicineTextFieldjTextField7ActionPerformed

    private void resourceListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_resourceListValueChanged
        if (resourceList.isSelectedIndex(0)) {
            numberOfEducationSuppliesTextField.setEnabled(true);
            numberOfTeacherTextField.setEnabled(true);
        } else {
            numberOfEducationSuppliesTextField.setEnabled(false);
            numberOfTeacherTextField.setEnabled(false);
        }
        if (resourceList.isSelectedIndex(1)) {
            numberOfDoctorTextField.setEnabled(true);
            nameOfMedicineTextField.setEnabled(true);
            quantityOfMedicineTextField.setEnabled(true);
            typeOfMedicineTextField.setEnabled(true);
        } else {
            numberOfDoctorTextField.setEnabled(false);
            nameOfMedicineTextField.setEnabled(false);
            quantityOfMedicineTextField.setEnabled(false);
            typeOfMedicineTextField.setEnabled(false);

        }
        if (resourceList.isSelectedIndex(2)) {
            numberOfPacketsTestField.setEnabled(true);
        } else {
            numberOfPacketsTestField.setEnabled(false);

        }
        if (resourceList.isSelectedIndex(3)) {
            moneyTextField.setEnabled(true);
        } else {
            moneyTextField.setEnabled(false);

        }
    }//GEN-LAST:event_resourceListValueChanged


    private void backJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backJButtonMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonMouseClicked

    private void buttonDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDashboardMouseClicked
        UserRoleWorkAreaJPanel userRoleWorkAreaJPanel = new UserRoleWorkAreaJPanel(userProcessContainer, account, system);
        userProcessContainer.add("userRoleWorkAreaJPanel", userRoleWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_buttonDashboardMouseClicked

    private void requestRaiseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestRaiseButtonMouseClicked
        // TODO add your handling code here:
        RequestResourceJPanel requestJPanel = new RequestResourceJPanel(userProcessContainer, account, system);
        userProcessContainer.add("requestJPanel", requestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestRaiseButtonMouseClicked

    private void requestRaiseButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestRaiseButton1MouseClicked
        // TODO add your handling code here:
        ViewRequestsJPanel viewRequestJPanel = new ViewRequestsJPanel(userProcessContainer, account, system);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add(viewRequestJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestRaiseButton1MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backJButton;
    private javax.swing.JPanel buttonDashboard;
    private javax.swing.JTextArea descriptionTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox localityComboField;
    private javax.swing.JTextField moneyTextField;
    private javax.swing.JTextField nameOfMedicineTextField;
    private javax.swing.JTextField numberOfDoctorTextField;
    private javax.swing.JTextField numberOfEducationSuppliesTextField;
    private javax.swing.JTextField numberOfPacketsTestField;
    private javax.swing.JTextField numberOfTeacherTextField;
    private javax.swing.JTextField quantityOfMedicineTextField;
    private javax.swing.JPanel raiseRequestButton;
    private javax.swing.JTextField requestIdTextField;
    private javax.swing.JPanel requestRaiseButton;
    private javax.swing.JPanel requestRaiseButton1;
    private javax.swing.JComboBox requestTypeComboField;
    private javax.swing.JList resourceList;
    private javax.swing.JTextField typeOfMedicineTextField;
    // End of variables declaration//GEN-END:variables
}
