/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.NGOEnterprise;
import Business.Resources.EducationResource;
import Business.Resources.FoodResource;
import Business.Resources.HealthResource;
import Business.Resources.MoneyResource;
import Business.Resources.Resource;
import Business.Utility.UtitlityMethods;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.swing.JPanel;
import userinterface.MainPanel;

/**
 *
 * @author shukl
 */
public class AddResourceJpanel extends javax.swing.JPanel {

    /**
     * Creates new form AddResourceJpanel
     */
    private JPanel userProcessContainer;
    private Map<String, List<Resource>> resourcesOffered;
    private Enterprise enterprise;
    private EcoSystem system;

    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public AddResourceJpanel(JPanel userProcessContainer, Map<String, List<Resource>> resourcesOffered, EcoSystem system) {

        initComponents();
        numberOfFoodPacksTextField.setEditable(false);
        numberOfFoodPacksTextField.setEnabled(false);
        moneyTextField.setEditable(false);
        moneyTextField.setEnabled(false);
        nameOfMedicineTextField.setEditable(false);
        nameOfMedicineTextField.setEnabled(false);
        medicineTypeTextField.setEditable(false);
        medicineTypeTextField.setEnabled(false);
        quantityOfMedicineTextField.setEditable(false);
        quantityOfMedicineTextField.setEnabled(false);
        numberOFDoctorsTextField.setEditable(false);
        numberOFDoctorsTextField.setEnabled(false);
        numberOfEducationTextField.setEditable(false);
        numberOfEducationTextField.setEnabled(false);
        numberOfTeachersTextField.setEditable(false);
        numberOfTeachersTextField.setEnabled(false);
        foodCheckBox.setVisible(false);
        moneyCheckBox.setVisible(false);
        educationCheckBox.setVisible(false);
        medicalCheckBox.setVisible(false);
        this.userProcessContainer = userProcessContainer;
        this.resourcesOffered = resourcesOffered;
        this.system = system;
        populateFields();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        foodCheckBox = new javax.swing.JCheckBox();
        educationCheckBox = new javax.swing.JCheckBox();
        medicalCheckBox = new javax.swing.JCheckBox();
        moneyCheckBox = new javax.swing.JCheckBox();
        lable1 = new javax.swing.JLabel();
        numberOfEducationTextField = new javax.swing.JTextField();
        numberOfTeachersTextField = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        numberOfFoodPacksTextField = new javax.swing.JTextField();
        nameOfMedicineTextField = new javax.swing.JTextField();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        medicineTypeTextField = new javax.swing.JTextField();
        label6 = new javax.swing.JLabel();
        numberOFDoctorsTextField = new javax.swing.JTextField();
        moneyTextField = new javax.swing.JTextField();
        label7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        expiryDateTextField = new javax.swing.JTextField();
        label8 = new javax.swing.JLabel();
        quantityOfMedicineTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backJButton = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        addResourceButton = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonDashboard = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        raiseCSRRequestButton = new javax.swing.JPanel();
        ngoFunctionLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        manageUserAccount = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        manageResourceButton = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        viewRequestsButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        manageEmployeeButton = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        manageReport = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        viewResourceRequestsButton = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ADD NEW RESOURCES");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        foodCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        foodCheckBox.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        foodCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        foodCheckBox.setText("Food");
        foodCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(foodCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        educationCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        educationCheckBox.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        educationCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        educationCheckBox.setText("Education");
        educationCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                educationCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(educationCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        medicalCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        medicalCheckBox.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        medicalCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        medicalCheckBox.setText("Medical");
        medicalCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(medicalCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        moneyCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        moneyCheckBox.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        moneyCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        moneyCheckBox.setText("Monitary");
        moneyCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(moneyCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        lable1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lable1.setForeground(new java.awt.Color(255, 255, 255));
        lable1.setText("No of education Supplies");
        jPanel1.add(lable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 187, -1, -1));

        numberOfEducationTextField.setEditable(false);
        numberOfEducationTextField.setBackground(new java.awt.Color(255, 255, 255));
        numberOfEducationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfEducationTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(numberOfEducationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 131, -1));

        numberOfTeachersTextField.setEditable(false);
        numberOfTeachersTextField.setBackground(new java.awt.Color(255, 255, 255));
        numberOfTeachersTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfTeachersTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(numberOfTeachersTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 131, -1));

        label2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("No of Teachers Offered");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 220, -1, -1));

        label3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("No of Food packets Offered");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 259, -1, -1));

        numberOfFoodPacksTextField.setEditable(false);
        numberOfFoodPacksTextField.setBackground(new java.awt.Color(255, 255, 255));
        numberOfFoodPacksTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfFoodPacksTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(numberOfFoodPacksTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 131, -1));

        nameOfMedicineTextField.setEditable(false);
        nameOfMedicineTextField.setBackground(new java.awt.Color(255, 255, 255));
        nameOfMedicineTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameOfMedicineTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nameOfMedicineTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 131, -1));

        label4.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("Name of medicine ");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        label5.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("Medicine Type");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        medicineTypeTextField.setEditable(false);
        medicineTypeTextField.setBackground(new java.awt.Color(255, 255, 255));
        medicineTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineTypeTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(medicineTypeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 131, -1));

        label6.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setText("No of doctors offered");
        jPanel1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        numberOFDoctorsTextField.setEditable(false);
        numberOFDoctorsTextField.setBackground(new java.awt.Color(255, 255, 255));
        numberOFDoctorsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOFDoctorsTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(numberOFDoctorsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 131, -1));

        moneyTextField.setEditable(false);
        moneyTextField.setBackground(new java.awt.Color(255, 255, 255));
        moneyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(moneyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 131, -1));

        label7.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setText("Money Offered in USD ");
        jPanel1.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Expiry Date");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, -1));

        expiryDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiryDateTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(expiryDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 131, -1));

        label8.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 255, 255));
        label8.setText("Quantity of medicines offered");
        jPanel1.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        quantityOfMedicineTextField.setEditable(false);
        quantityOfMedicineTextField.setBackground(new java.awt.Color(255, 255, 255));
        quantityOfMedicineTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityOfMedicineTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(quantityOfMedicineTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 338, 130, -1));

        jLabel1.setText("$");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 30, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Resources Offered");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 102, -1, -1));

        backJButton.setBackground(new java.awt.Color(0, 0, 0));
        backJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        backJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backJButtonMouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("BACK");

        javax.swing.GroupLayout backJButtonLayout = new javax.swing.GroupLayout(backJButton);
        backJButton.setLayout(backJButtonLayout);
        backJButtonLayout.setHorizontalGroup(
            backJButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backJButtonLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel21)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        backJButtonLayout.setVerticalGroup(
            backJButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backJButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, -1, -1));

        addResourceButton.setBackground(new java.awt.Color(0, 0, 0));
        addResourceButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        addResourceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addResourceButtonMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ADD RESOURCE");

        javax.swing.GroupLayout addResourceButtonLayout = new javax.swing.GroupLayout(addResourceButton);
        addResourceButton.setLayout(addResourceButtonLayout);
        addResourceButtonLayout.setHorizontalGroup(
            addResourceButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addResourceButtonLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel22)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        addResourceButtonLayout.setVerticalGroup(
            addResourceButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addResourceButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(addResourceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 645, 630));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-unicast-filled-50.png"))); // NOI18N
        add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 60, 50));

        jLabel32.setBackground(new java.awt.Color(22, 16, 16));
        jLabel32.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(22, 16, 16));
        jLabel32.setText("MANAGE RESOURCES");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 330, 70));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 2020, 13));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 13, -1, -1));

        jLabel62.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel62.setText("a corporate social responsiblity request");
        jPanel3.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 320, -1));

        jLabel63.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel63.setText("Click on \"Raise CSR request\"  to raise ");
        jPanel3.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 320, 26));

        jLabel64.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel64.setText("Click on \"Manage user account\"  to view and");
        jPanel3.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 340, 30));

        jLabel65.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel65.setText("  and update the user information.");
        jPanel3.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 320, 20));
        jPanel3.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 130, -1, 100));

        jLabel67.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel67.setText("Click on \"Manage organization and employee\" ");
        jPanel3.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 350, 26));

        jLabel68.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel68.setText(" to add organization or employee");
        jPanel3.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 320, -1));

        jLabel34.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel34.setText("Click on \"Manage resource\"  to manage");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 320, 26));

        jLabel35.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel35.setText("the resource of corporate");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 320, -1));

        jLabel41.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel41.setText("Click on \"Manage user account\"  to view and");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 50, 340, 30));

        jLabel42.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel42.setText("  and update the user information.");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 80, 320, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-admin-settings-male-24.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 40, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-coins-filled-50.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 60, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-plus-filled-50.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, 60, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-unicast-filled-50.png"))); // NOI18N
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 60, 50));

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user-groups-filled-50.png"))); // NOI18N
        jPanel3.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 60, 50));

        jLabel44.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel44.setText("Click on \"Manage Reports\"  to view and");
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 150, 340, 30));

        jLabel45.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel45.setText("  and update the user information.");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 180, 320, 20));
        jPanel3.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 150, 60, 50));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 740, 2290, 250));

        jPanel4.setBackground(new java.awt.Color(22, 16, 16));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setBackground(new java.awt.Color(102, 102, 102));
        jLabel26.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("Helping");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 13, 170, 70));

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Hands");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 13, 140, 70));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 430, 13));

        buttonDashboard.setBackground(new java.awt.Color(22, 16, 16));
        buttonDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDashboardMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Dashboard");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pen-tablet.png"))); // NOI18N

        javax.swing.GroupLayout buttonDashboardLayout = new javax.swing.GroupLayout(buttonDashboard);
        buttonDashboard.setLayout(buttonDashboardLayout);
        buttonDashboardLayout.setHorizontalGroup(
            buttonDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonDashboardLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );
        buttonDashboardLayout.setVerticalGroup(
            buttonDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonDashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(36, 36, 36))
            .addGroup(buttonDashboardLayout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(buttonDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 116, 430, 55));

        raiseCSRRequestButton.setBackground(new java.awt.Color(22, 16, 16));
        raiseCSRRequestButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raiseCSRRequestButtonMouseClicked(evt);
            }
        });
        raiseCSRRequestButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ngoFunctionLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        ngoFunctionLabel.setForeground(new java.awt.Color(204, 204, 204));
        ngoFunctionLabel.setText("Raise CSR Request");
        raiseCSRRequestButton.add(ngoFunctionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));
        raiseCSRRequestButton.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 0, -1, 38));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coin-stack-1.png"))); // NOI18N
        raiseCSRRequestButton.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(raiseCSRRequestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 173, 430, 56));

        manageUserAccount.setBackground(new java.awt.Color(22, 16, 16));
        manageUserAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageUserAccountMouseClicked(evt);
            }
        });
        manageUserAccount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Manage User Account");
        manageUserAccount.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 22, -1, -1));
        manageUserAccount.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 0, -1, 90));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id-card-1.png"))); // NOI18N
        manageUserAccount.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(manageUserAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 303, 430, 61));

        manageResourceButton.setBackground(new java.awt.Color(204, 204, 204));
        manageResourceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageResourceButtonMouseClicked(evt);
            }
        });
        manageResourceButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Manage Resource ");
        manageResourceButton.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));
        manageResourceButton.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, 90));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user-add.png"))); // NOI18N
        manageResourceButton.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(manageResourceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 366, 430, 64));

        viewRequestsButton.setBackground(new java.awt.Color(22, 16, 16));
        viewRequestsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewRequestsButtonMouseClicked(evt);
            }
        });
        viewRequestsButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("View open request");
        viewRequestsButton.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email-outbox.png"))); // NOI18N
        viewRequestsButton.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(viewRequestsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 437, 430, 63));

        manageEmployeeButton.setBackground(new java.awt.Color(22, 16, 16));
        manageEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageEmployeeButtonMouseClicked(evt);
            }
        });
        manageEmployeeButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Manage Organization and Employee");
        manageEmployeeButton.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));
        manageEmployeeButton.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, 90));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/building-6.png"))); // NOI18N
        manageEmployeeButton.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(manageEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, 430, 60));

        manageReport.setBackground(new java.awt.Color(22, 16, 16));
        manageReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageReportMouseClicked(evt);
            }
        });
        manageReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 204));
        jLabel28.setText("Manage Reports");
        manageReport.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file-notes-document.png"))); // NOI18N
        manageReport.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(manageReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 507, 430, 63));

        logoutJButton.setBackground(new java.awt.Color(22, 16, 16));
        logoutJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutJButtonMouseClicked(evt);
            }
        });
        logoutJButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("Logout");
        logoutJButton.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 199, -1));
        logoutJButton.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 23, 39, -1));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lock-unlock-1.png"))); // NOI18N
        logoutJButton.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 30));

        jPanel4.add(logoutJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 647, 430, -1));

        viewResourceRequestsButton.setBackground(new java.awt.Color(22, 16, 16));
        viewResourceRequestsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewResourceRequestsButtonMouseClicked(evt);
            }
        });
        viewResourceRequestsButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("View Resource requests");
        viewResourceRequestsButton.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email-outbox.png"))); // NOI18N
        viewResourceRequestsButton.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 30));

        jPanel4.add(viewResourceRequestsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 577, 406, 63));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 990));
    }// </editor-fold>//GEN-END:initComponents

    private void foodCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodCheckBoxActionPerformed
        if (foodCheckBox.isSelected()) {
            numberOfFoodPacksTextField.setEditable(true);
            numberOfFoodPacksTextField.setEnabled(true);
        } else {
            numberOfFoodPacksTextField.setEditable(false);
            numberOfFoodPacksTextField.setEnabled(false);
        }
    }//GEN-LAST:event_foodCheckBoxActionPerformed

    private void moneyCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyCheckBoxActionPerformed
        if (moneyCheckBox.isSelected()) {
            moneyTextField.setEditable(true);
            moneyTextField.setEnabled(true);

        } else {
            moneyTextField.setEditable(false);
            moneyTextField.setEnabled(false);
        }
    }//GEN-LAST:event_moneyCheckBoxActionPerformed

    private void medicalCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalCheckBoxActionPerformed
        if (medicalCheckBox.isSelected()) {
            nameOfMedicineTextField.setEditable(true);
            nameOfMedicineTextField.setEnabled(true);
            medicineTypeTextField.setEditable(true);
            medicineTypeTextField.setEnabled(true);
            quantityOfMedicineTextField.setEditable(true);
            quantityOfMedicineTextField.setEnabled(true);
            numberOFDoctorsTextField.setEditable(true);
            numberOFDoctorsTextField.setEnabled(true);

        } else {
            nameOfMedicineTextField.setEditable(false);
            nameOfMedicineTextField.setEnabled(false);
            medicineTypeTextField.setEditable(false);
            medicineTypeTextField.setEnabled(false);
            quantityOfMedicineTextField.setEditable(false);
            quantityOfMedicineTextField.setEnabled(false);
            numberOFDoctorsTextField.setEditable(false);
            numberOFDoctorsTextField.setEnabled(false);
        }
    }//GEN-LAST:event_medicalCheckBoxActionPerformed

    private void educationCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_educationCheckBoxActionPerformed
        if (educationCheckBox.isSelected()) {
            numberOfEducationTextField.setEditable(true);
            numberOfEducationTextField.setEnabled(true);
            numberOfTeachersTextField.setEditable(true);
            numberOfTeachersTextField.setEnabled(true);

        } else {
            numberOfEducationTextField.setEditable(false);
            numberOfEducationTextField.setEnabled(false);
            numberOfTeachersTextField.setEditable(false);
            numberOfTeachersTextField.setEnabled(false);
        }
    }//GEN-LAST:event_educationCheckBoxActionPerformed

    private void numberOfEducationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfEducationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfEducationTextFieldActionPerformed

    private void numberOfTeachersTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfTeachersTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfTeachersTextFieldActionPerformed

    private void numberOfFoodPacksTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfFoodPacksTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfFoodPacksTextFieldActionPerformed

    private void quantityOfMedicineTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityOfMedicineTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityOfMedicineTextFieldActionPerformed

    private void nameOfMedicineTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameOfMedicineTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameOfMedicineTextFieldActionPerformed

    private void numberOFDoctorsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOFDoctorsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOFDoctorsTextFieldActionPerformed

    private void moneyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyTextFieldActionPerformed

    private void expiryDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiryDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiryDateTextFieldActionPerformed

    private void medicineTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineTypeTextFieldActionPerformed

    private void backJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backJButtonMouseClicked

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageResourcesJPanel mrjp = (ManageResourcesJPanel) component;
        mrjp.populateData();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonMouseClicked

    private void addResourceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addResourceButtonMouseClicked
        // TODO add your handling code here:
        if (moneyCheckBox.isSelected()) {
            MoneyResource moneyResource = new MoneyResource(Integer.parseInt(moneyTextField.getText()), "USD", "Money", EcoSystem.counter++);
            moneyResource.setExpiryDate(UtitlityMethods.getDateFromString(expiryDateTextField.getText()));
            moneyResource.setCreatedDate(new Date());
            resourcesOffered.get("Money").add(moneyResource);

        }
        if (foodCheckBox.isSelected()) {
            FoodResource foodResource = new FoodResource(Integer.parseInt(numberOfFoodPacksTextField.getText()), "Food", EcoSystem.counter++);
            foodResource.setExpiryDate(UtitlityMethods.getDateFromString(expiryDateTextField.getText()));
            foodResource.setCreatedDate(new Date());
            resourcesOffered.get("Food").add(foodResource);
        }
        if (medicalCheckBox.isSelected()) {
            HealthResource healthResource = new HealthResource(nameOfMedicineTextField.getText(), medicineTypeTextField.getText(), Integer.parseInt(quantityOfMedicineTextField.getText()), Integer.parseInt(numberOFDoctorsTextField.getText()), "Health", EcoSystem.counter++);
            healthResource.setExpiryDate(UtitlityMethods.getDateFromString(expiryDateTextField.getText()));
            healthResource.setCreatedDate(new Date());
            resourcesOffered.get("Health").add(healthResource);
        }
        if (educationCheckBox.isSelected()) {
            EducationResource educationResource = new EducationResource(Integer.parseInt(numberOfEducationTextField.getText()), Integer.parseInt(numberOfTeachersTextField.getText()), "Education", EcoSystem.counter++);
            educationResource.setExpiryDate(UtitlityMethods.getDateFromString(expiryDateTextField.getText()));
            educationResource.setCreatedDate(new Date());
            resourcesOffered.get("Education").add(educationResource);
        }
    }//GEN-LAST:event_addResourceButtonMouseClicked

    private void buttonDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDashboardMouseClicked
        AdminWorkAreaJPanel systemAdminWorkAreaJPanel = new AdminWorkAreaJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("systemAdminWorkAreaJPanel", systemAdminWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_buttonDashboardMouseClicked

    private void raiseCSRRequestButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raiseCSRRequestButtonMouseClicked
        if (enterprise.getEnterpriseType().equals(NGOEnterprise.EnterpriseType.NGO)) {
            StartFundRaiser startFundRaiser = new StartFundRaiser(userProcessContainer, enterprise, system);
            userProcessContainer.add("startFundRaiser", startFundRaiser);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
            RaiseCSRActivityJPanel raiseCsrActivityJPanel = new RaiseCSRActivityJPanel(userProcessContainer, enterprise, system);
            userProcessContainer.add("raiseCsrActivityJPanel", raiseCsrActivityJPanel);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_raiseCSRRequestButtonMouseClicked

    private void manageUserAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserAccountMouseClicked
        ManageUserAccountJPanel manageUserAccountJPanel = new ManageUserAccountJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("manageUserAccountJPanel", manageUserAccountJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageUserAccountMouseClicked

    private void manageResourceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageResourceButtonMouseClicked
        ManageResourcesJPanel manageResourcesJPanel = new ManageResourcesJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("manageResourcesJPanel", manageResourcesJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageResourceButtonMouseClicked

    private void viewRequestsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRequestsButtonMouseClicked
        if (enterprise.getEnterpriseType().equals(NGOEnterprise.EnterpriseType.NGO)) {
            ViewFundRaiserRequestsJPanel viewRequestsJPanel = new ViewFundRaiserRequestsJPanel(userProcessContainer, enterprise, system);
            userProcessContainer.add("viewRequestsJPanel", viewRequestsJPanel);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
            ViewCSRRequestsJPanel viewRequestsJPanel = new ViewCSRRequestsJPanel(userProcessContainer, enterprise, system);
            userProcessContainer.add("viewRequestsJPanel", viewRequestsJPanel);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_viewRequestsButtonMouseClicked

    private void manageEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEmployeeButtonMouseClicked
        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEmployeeButtonMouseClicked

    private void manageReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageReportMouseClicked
        // TODO add your handling code here:
        ManageReports manageReports = new ManageReports(userProcessContainer, enterprise, system);
        userProcessContainer.add("manageReports", manageReports);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageReportMouseClicked

    private void logoutJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutJButtonMouseClicked
        userProcessContainer.removeAll();
        dB4OUtil.storeSystem(system);
        MainPanel mainJPanel = new MainPanel();
        userProcessContainer.add("mainJPanel", mainJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_logoutJButtonMouseClicked

    private void viewResourceRequestsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewResourceRequestsButtonMouseClicked

        ViewOpenResourceRequestsJPanel viewOpenResourceRequestsJPanel = new ViewOpenResourceRequestsJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("viewOpenResourceRequestsJPanel", viewOpenResourceRequestsJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewResourceRequestsButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addResourceButton;
    private javax.swing.JPanel backJButton;
    private javax.swing.JPanel buttonDashboard;
    private javax.swing.JCheckBox educationCheckBox;
    private javax.swing.JTextField expiryDateTextField;
    private javax.swing.JCheckBox foodCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel lable1;
    private javax.swing.JPanel logoutJButton;
    private javax.swing.JPanel manageEmployeeButton;
    private javax.swing.JPanel manageReport;
    private javax.swing.JPanel manageResourceButton;
    private javax.swing.JPanel manageUserAccount;
    private javax.swing.JCheckBox medicalCheckBox;
    private javax.swing.JTextField medicineTypeTextField;
    private javax.swing.JCheckBox moneyCheckBox;
    private javax.swing.JTextField moneyTextField;
    private javax.swing.JTextField nameOfMedicineTextField;
    private javax.swing.JLabel ngoFunctionLabel;
    private javax.swing.JTextField numberOFDoctorsTextField;
    private javax.swing.JTextField numberOfEducationTextField;
    private javax.swing.JTextField numberOfFoodPacksTextField;
    private javax.swing.JTextField numberOfTeachersTextField;
    private javax.swing.JTextField quantityOfMedicineTextField;
    private javax.swing.JPanel raiseCSRRequestButton;
    private javax.swing.JPanel viewRequestsButton;
    private javax.swing.JPanel viewResourceRequestsButton;
    // End of variables declaration//GEN-END:variables

    private void populateFields() {

        for (String s : resourcesOffered.keySet()) {
            if (s.equalsIgnoreCase("Food")) {
                foodCheckBox.setSelected(false);
                foodCheckBox.setEnabled(true);
                foodCheckBox.setVisible(true);
            }
            if (s.equalsIgnoreCase("Education")) {
                educationCheckBox.setSelected(false);
                educationCheckBox.setEnabled(true);
                educationCheckBox.setVisible(true);
            }
            if (s.equalsIgnoreCase("Health")) {
                medicalCheckBox.setSelected(false);
                medicalCheckBox.setEnabled(true);
                medicalCheckBox.setVisible(true);
            }
            if (s.equalsIgnoreCase("Money")) {
                moneyCheckBox.setSelected(false);
                moneyCheckBox.setEnabled(true);
                moneyCheckBox.setVisible(true);
            }

        }
    }
}
