/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.NGOEnterprise;
import Business.Resources.EducationResource;
import Business.Resources.FoodResource;
import Business.Resources.HealthResource;
import Business.Resources.MoneyResource;
import Business.Resources.Resource;
import java.awt.CardLayout;
import java.util.List;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.MainPanel;

/**
 *
 * @author shukl
 */
public class ManageResourcesJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    Map<String, List<Resource>> resourcesOffered;
    private Enterprise enterprise;
    private EcoSystem system;
private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    /**
     * Creates new form ManageResourcesJPanel
     */
    public ManageResourcesJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.resourcesOffered = enterprise.getResourcesOffered();
        this.system = system;
        this.enterprise = enterprise;
        populateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageResourceJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        addResources = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        backBtn = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        viewDetailedResource = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel47 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonDashboard = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        raiseCSRRequestButton = new javax.swing.JPanel();
        ngoFunctionLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        manageUserAccount = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        manageResourceButton = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        viewRequestsButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        manageEmployeeButton = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        manageReport = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        viewResourceRequestsButton = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        manageResourceJTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        manageResourceJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Resource name", "Start Date", "Expiry Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        manageResourceJTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(manageResourceJTable);
        manageResourceJTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIEW EXISTING DETAILS");

        addResources.setBackground(new java.awt.Color(0, 0, 0));
        addResources.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addResourcesMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ADD RESOURCE");

        javax.swing.GroupLayout addResourcesLayout = new javax.swing.GroupLayout(addResources);
        addResources.setLayout(addResourcesLayout);
        addResourcesLayout.setHorizontalGroup(
            addResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addResourcesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(33, 33, 33))
        );
        addResourcesLayout.setVerticalGroup(
            addResourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addResourcesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("BACK");

        javax.swing.GroupLayout backBtnLayout = new javax.swing.GroupLayout(backBtn);
        backBtn.setLayout(backBtnLayout);
        backBtnLayout.setHorizontalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backBtnLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel21)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        backBtnLayout.setVerticalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        viewDetailedResource.setBackground(new java.awt.Color(0, 0, 0));
        viewDetailedResource.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        viewDetailedResource.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewDetailedResourceMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("VIEW DETAILS");

        javax.swing.GroupLayout viewDetailedResourceLayout = new javax.swing.GroupLayout(viewDetailedResource);
        viewDetailedResource.setLayout(viewDetailedResourceLayout);
        viewDetailedResourceLayout.setHorizontalGroup(
            viewDetailedResourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewDetailedResourceLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(21, 21, 21))
        );
        viewDetailedResourceLayout.setVerticalGroup(
            viewDetailedResourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewDetailedResourceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(viewDetailedResource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addResources, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewDetailedResource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addResources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 206, -1, -1));

        jLabel9.setBackground(new java.awt.Color(22, 16, 16));
        jLabel9.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(22, 16, 16));
        jLabel9.setText("MANAGE RESOURCES");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 7, 330, 70));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 90, 2020, 10));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-unicast-filled-50.png"))); // NOI18N
        add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 27, 60, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 13, -1, -1));

        jLabel46.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel46.setText("a corporate social responsiblity request");
        jPanel3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 320, -1));

        jLabel53.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel53.setText("Click on \"Raise CSR request\"  to raise ");
        jPanel3.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 320, 26));

        jLabel54.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel54.setText("Click on \"Manage user account\"  to view and");
        jPanel3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 340, 30));

        jLabel55.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel55.setText("  and update the user information.");
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 320, 20));
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 130, -1, 100));

        jLabel31.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel31.setText("Click on \"Manage organization and employee\" ");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 350, 26));

        jLabel32.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel32.setText(" to add organization or employee");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 320, -1));

        jLabel34.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel34.setText("Click on \"Manage resource\"  to manage");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 320, 26));

        jLabel35.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel35.setText("the resource of corporate");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 320, -1));

        jLabel41.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel41.setText("Click on \"Manage user account\"  to view and");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 50, 340, 30));

        jLabel42.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel42.setText("  and update the user information.");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 80, 320, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-admin-settings-male-24.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 40, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-coins-filled-50.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 60, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-plus-filled-50.png"))); // NOI18N
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, 60, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-unicast-filled-50.png"))); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 60, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user-groups-filled-50.png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 60, 50));

        jLabel44.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel44.setText("Click on \"Manage Reports\"  to view and");
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 150, 340, 30));

        jLabel45.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel45.setText("  and update the user information.");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 180, 320, 20));
        jPanel3.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 150, 60, 50));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 740, 2290, 250));

        jPanel4.setBackground(new java.awt.Color(22, 16, 16));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setBackground(new java.awt.Color(102, 102, 102));
        jLabel26.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("Helping");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 13, 170, 70));

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Hands");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 13, 140, 70));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 430, 13));

        buttonDashboard.setBackground(new java.awt.Color(22, 16, 16));
        buttonDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDashboardMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Dashboard");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pen-tablet.png"))); // NOI18N

        javax.swing.GroupLayout buttonDashboardLayout = new javax.swing.GroupLayout(buttonDashboard);
        buttonDashboard.setLayout(buttonDashboardLayout);
        buttonDashboardLayout.setHorizontalGroup(
            buttonDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonDashboardLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );
        buttonDashboardLayout.setVerticalGroup(
            buttonDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonDashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(36, 36, 36))
            .addGroup(buttonDashboardLayout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(buttonDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 116, 430, 55));

        raiseCSRRequestButton.setBackground(new java.awt.Color(22, 16, 16));
        raiseCSRRequestButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raiseCSRRequestButtonMouseClicked(evt);
            }
        });
        raiseCSRRequestButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ngoFunctionLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        ngoFunctionLabel.setForeground(new java.awt.Color(204, 204, 204));
        ngoFunctionLabel.setText("Raise CSR Request");
        raiseCSRRequestButton.add(ngoFunctionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));
        raiseCSRRequestButton.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 0, -1, 38));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coin-stack-1.png"))); // NOI18N
        raiseCSRRequestButton.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(raiseCSRRequestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 173, 430, 56));

        manageUserAccount.setBackground(new java.awt.Color(22, 16, 16));
        manageUserAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageUserAccountMouseClicked(evt);
            }
        });
        manageUserAccount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Manage User Account");
        manageUserAccount.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 22, -1, -1));
        manageUserAccount.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 0, -1, 90));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id-card-1.png"))); // NOI18N
        manageUserAccount.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(manageUserAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 303, 430, 61));

        manageResourceButton.setBackground(new java.awt.Color(204, 204, 204));
        manageResourceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageResourceButtonMouseClicked(evt);
            }
        });
        manageResourceButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Manage Resource ");
        manageResourceButton.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));
        manageResourceButton.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, 90));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user-add.png"))); // NOI18N
        manageResourceButton.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(manageResourceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 366, 430, 64));

        viewRequestsButton.setBackground(new java.awt.Color(22, 16, 16));
        viewRequestsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewRequestsButtonMouseClicked(evt);
            }
        });
        viewRequestsButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("View open request");
        viewRequestsButton.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email-outbox.png"))); // NOI18N
        viewRequestsButton.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(viewRequestsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 437, 430, 63));

        manageEmployeeButton.setBackground(new java.awt.Color(22, 16, 16));
        manageEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageEmployeeButtonMouseClicked(evt);
            }
        });
        manageEmployeeButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Manage Organization and Employee");
        manageEmployeeButton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));
        manageEmployeeButton.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, 90));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/building-6.png"))); // NOI18N
        manageEmployeeButton.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(manageEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, 430, 60));

        manageReport.setBackground(new java.awt.Color(22, 16, 16));
        manageReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageReportMouseClicked(evt);
            }
        });
        manageReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 204));
        jLabel28.setText("Manage Reports");
        manageReport.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file-notes-document.png"))); // NOI18N
        manageReport.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(manageReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 507, 430, 63));

        logoutJButton.setBackground(new java.awt.Color(22, 16, 16));
        logoutJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutJButtonMouseClicked(evt);
            }
        });
        logoutJButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("Logout");
        logoutJButton.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 199, -1));
        logoutJButton.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 23, 39, -1));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lock-unlock-1.png"))); // NOI18N
        logoutJButton.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 30));

        jPanel4.add(logoutJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 647, 430, -1));

        viewResourceRequestsButton.setBackground(new java.awt.Color(22, 16, 16));
        viewResourceRequestsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewResourceRequestsButtonMouseClicked(evt);
            }
        });
        viewResourceRequestsButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("View Resource requests");
        viewResourceRequestsButton.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email-outbox.png"))); // NOI18N
        viewResourceRequestsButton.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 30));

        jPanel4.add(viewResourceRequestsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 577, 406, 63));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 990));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnMouseClicked

    private void viewDetailedResourceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDetailedResourceMouseClicked
        // TODO add your handling code here:

        int selectedRow = manageResourceJTable.getSelectedRow();

        if (selectedRow < 0) {

            return;
        }

        Resource resource = null;
        if (manageResourceJTable.getValueAt(selectedRow, 0) instanceof EducationResource) {
            resource = (EducationResource)manageResourceJTable.getValueAt(selectedRow, 0);
        } else if (manageResourceJTable.getValueAt(selectedRow, 0) instanceof FoodResource) {
            resource = (FoodResource)manageResourceJTable.getValueAt(selectedRow, 0);
        } else if (manageResourceJTable.getValueAt(selectedRow, 0) instanceof HealthResource) {
            resource = (HealthResource)manageResourceJTable.getValueAt(selectedRow, 0);
        } else if (manageResourceJTable.getValueAt(selectedRow, 0) instanceof MoneyResource) {
            resource = (MoneyResource)manageResourceJTable.getValueAt(selectedRow, 0);
        }

        ViewDetailResourceJpanel viewDetailResourceJpanel = new ViewDetailResourceJpanel(userProcessContainer, resource, system);
        userProcessContainer.add("viewDetailResourceJpanel", viewDetailResourceJpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_viewDetailedResourceMouseClicked

    private void addResourcesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addResourcesMouseClicked
        // TODO add your handling code here:

        AddResourceJpanel addResourceJpanel = new AddResourceJpanel(userProcessContainer, resourcesOffered, system);
        userProcessContainer.add("addResourceJpanel", addResourceJpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_addResourcesMouseClicked

    private void buttonDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDashboardMouseClicked
        AdminWorkAreaJPanel systemAdminWorkAreaJPanel = new AdminWorkAreaJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("systemAdminWorkAreaJPanel", systemAdminWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_buttonDashboardMouseClicked

    private void raiseCSRRequestButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raiseCSRRequestButtonMouseClicked
        if (enterprise.getEnterpriseType().equals(NGOEnterprise.EnterpriseType.NGO)) {
            StartFundRaiser startFundRaiser = new StartFundRaiser(userProcessContainer, enterprise, system);
            userProcessContainer.add("startFundRaiser", startFundRaiser);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
            RaiseCSRActivityJPanel raiseCsrActivityJPanel = new RaiseCSRActivityJPanel(userProcessContainer, enterprise, system);
            userProcessContainer.add("raiseCsrActivityJPanel", raiseCsrActivityJPanel);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_raiseCSRRequestButtonMouseClicked

    private void manageUserAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserAccountMouseClicked
        ManageUserAccountJPanel manageUserAccountJPanel = new ManageUserAccountJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("manageUserAccountJPanel", manageUserAccountJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageUserAccountMouseClicked

    private void manageResourceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageResourceButtonMouseClicked
        ManageResourcesJPanel manageResourcesJPanel = new ManageResourcesJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("manageResourcesJPanel", manageResourcesJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageResourceButtonMouseClicked

    private void viewRequestsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRequestsButtonMouseClicked
        if (enterprise.getEnterpriseType().equals(NGOEnterprise.EnterpriseType.NGO)) {
            ViewFundRaiserRequestsJPanel viewRequestsJPanel = new ViewFundRaiserRequestsJPanel(userProcessContainer, enterprise, system);
            userProcessContainer.add("viewRequestsJPanel", viewRequestsJPanel);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
            ViewCSRRequestsJPanel viewRequestsJPanel = new ViewCSRRequestsJPanel(userProcessContainer, enterprise, system);
            userProcessContainer.add("viewRequestsJPanel", viewRequestsJPanel);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_viewRequestsButtonMouseClicked

    private void manageEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEmployeeButtonMouseClicked
        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEmployeeButtonMouseClicked

    private void manageReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageReportMouseClicked
        // TODO add your handling code here:
        ManageReports manageReports = new ManageReports(userProcessContainer, enterprise, system);
        userProcessContainer.add("manageReports", manageReports);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageReportMouseClicked

    private void logoutJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutJButtonMouseClicked
        userProcessContainer.removeAll();
        dB4OUtil.storeSystem(system);
        MainPanel mainJPanel = new MainPanel();
        userProcessContainer.add("mainJPanel", mainJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_logoutJButtonMouseClicked

    private void viewResourceRequestsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewResourceRequestsButtonMouseClicked

        ViewOpenResourceRequestsJPanel viewOpenResourceRequestsJPanel = new ViewOpenResourceRequestsJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("viewOpenResourceRequestsJPanel", viewOpenResourceRequestsJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewResourceRequestsButtonMouseClicked

    public void populateData() {

        DefaultTableModel model = (DefaultTableModel) manageResourceJTable.getModel();

        model.setRowCount(0);

        for (Map.Entry<String, List<Resource>> resourceList : resourcesOffered.entrySet()) {
            for (Resource resources : resourceList.getValue()) {
                Object row[] = new Object[3];
                row[0] = resources;
                row[1] = resources.getCreatedDate();
                row[2] = resources.getExpiryDate();
                ((DefaultTableModel) manageResourceJTable.getModel()).addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addResources;
    private javax.swing.JPanel backBtn;
    private javax.swing.JPanel buttonDashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel logoutJButton;
    private javax.swing.JPanel manageEmployeeButton;
    private javax.swing.JPanel manageReport;
    private javax.swing.JPanel manageResourceButton;
    private javax.swing.JTable manageResourceJTable;
    private javax.swing.JPanel manageUserAccount;
    private javax.swing.JLabel ngoFunctionLabel;
    private javax.swing.JPanel raiseCSRRequestButton;
    private javax.swing.JPanel viewDetailedResource;
    private javax.swing.JPanel viewRequestsButton;
    private javax.swing.JPanel viewResourceRequestsButton;
    // End of variables declaration//GEN-END:variables
}
