/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.NGOEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.VolunteerOrganization;
import Business.Utility.UtitlityMethods;
import Business.WorkQueue.CSRActivityWorkRequest;
import Business.WorkQueue.FundRaisingActivityWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.MainPanel;

/**
 *
 * @author shukl
 */
public class StartFundRaiser extends javax.swing.JPanel {

    /**
     * Creates new form Test
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private Enterprise enterprise;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public StartFundRaiser(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.system = system;
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.requestIdTextField.setText(String.valueOf(EcoSystem.counter++));
        if (enterprise.getEnterpriseType().equals(NGOEnterprise.EnterpriseType.NGO)) {
            ngoFunctionLabel.setText("Start a Fund Raiser");
            windowLabel.setText("NGO WORK AREA");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        requestIdTextField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        descriptionTextField = new javax.swing.JTextArea();
        moneyTextField = new javax.swing.JTextField();
        projectDateTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        startFundRaiser = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        backJButton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        windowLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonDashboard = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        raiseCSRRequestButton = new javax.swing.JPanel();
        ngoFunctionLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        manageUserAccount = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        manageResourceButton = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        viewRequestsButton = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        manageEmployeeButton = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        manageReport = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        viewResourceRequestsButton = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("REQUEST ID");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("RAISE A NEW FUND RAISER");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 320, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("MONEY NEEDED FOR THIS PROJECT");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("DATE OF THE PROJECT");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        requestIdTextField.setText(" ");
        jPanel1.add(requestIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 166, -1));

        descriptionTextField.setColumns(20);
        descriptionTextField.setRows(5);
        jScrollPane3.setViewportView(descriptionTextField);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        moneyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyTextFieldjTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(moneyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 170, -1));

        projectDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectDateTextFieldjTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(projectDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 170, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("$");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 20, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("DESCRIPTION");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        startFundRaiser.setBackground(new java.awt.Color(0, 0, 0));
        startFundRaiser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        startFundRaiser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startFundRaiserMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Start a fund Raiser");

        javax.swing.GroupLayout startFundRaiserLayout = new javax.swing.GroupLayout(startFundRaiser);
        startFundRaiser.setLayout(startFundRaiserLayout);
        startFundRaiserLayout.setHorizontalGroup(
            startFundRaiserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startFundRaiserLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(29, 29, 29))
        );
        startFundRaiserLayout.setVerticalGroup(
            startFundRaiserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startFundRaiserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.add(startFundRaiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, -1, 50));

        backJButton.setBackground(new java.awt.Color(0, 0, 0));
        backJButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        backJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backJButtonMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("BACK");

        javax.swing.GroupLayout backJButtonLayout = new javax.swing.GroupLayout(backJButton);
        backJButton.setLayout(backJButtonLayout);
        backJButtonLayout.setHorizontalGroup(
            backJButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backJButtonLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(30, 30, 30))
        );
        backJButtonLayout.setVerticalGroup(
            backJButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, 50));

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("DESCRIPTION");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 710, 590));

        windowLabel.setBackground(new java.awt.Color(22, 16, 16));
        windowLabel.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        windowLabel.setForeground(new java.awt.Color(22, 16, 16));
        windowLabel.setText("RAISE CSR ACTIVITY");
        add(windowLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 250, 70));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 2320, 13));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 13, -1, -1));

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel21.setText("a corporate social responsiblity request");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 320, -1));

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel23.setText("Click on \"Raise CSR request\"  to raise ");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 320, 26));

        jLabel51.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel51.setText("Click on \"Manage user account\"  to view and");
        jPanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 340, 30));

        jLabel52.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel52.setText("  and update the user information.");
        jPanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 320, 20));
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 130, -1, 100));

        jLabel31.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel31.setText("Click on \"Manage organization and employee\" ");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 350, 26));

        jLabel32.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel32.setText(" to add organization or employee");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 320, -1));

        jLabel34.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel34.setText("Click on \"Manage resource\"  to manage");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 320, 26));

        jLabel35.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel35.setText("the resource of corporate");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 320, -1));

        jLabel41.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel41.setText("Click on \"Manage user account\"  to view and");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 50, 340, 30));

        jLabel42.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel42.setText("  and update the user information.");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 80, 320, 20));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-admin-settings-male-24.png"))); // NOI18N
        jPanel3.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 40, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-coins-filled-50.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 60, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-plus-filled-50.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, 60, 50));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-unicast-filled-50.png"))); // NOI18N
        jPanel3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 60, 50));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user-groups-filled-50.png"))); // NOI18N
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 60, 50));

        jLabel44.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel44.setText("Click on \"Manage Reports\"  to view and");
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 150, 340, 30));

        jLabel45.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel45.setText("  and update the user information.");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 180, 320, 20));
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 150, 60, 50));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 740, 2290, 250));

        jPanel4.setBackground(new java.awt.Color(22, 16, 16));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setBackground(new java.awt.Color(102, 102, 102));
        jLabel33.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("Helping");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 13, 170, 70));

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Hands");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 13, 140, 70));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 430, 13));

        buttonDashboard.setBackground(new java.awt.Color(204, 204, 204));
        buttonDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDashboardMouseClicked(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Dashboard");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pen-tablet.png"))); // NOI18N

        javax.swing.GroupLayout buttonDashboardLayout = new javax.swing.GroupLayout(buttonDashboard);
        buttonDashboard.setLayout(buttonDashboardLayout);
        buttonDashboardLayout.setHorizontalGroup(
            buttonDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonDashboardLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );
        buttonDashboardLayout.setVerticalGroup(
            buttonDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonDashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel46)
                .addGap(36, 36, 36))
            .addGroup(buttonDashboardLayout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(buttonDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 116, 430, 55));

        raiseCSRRequestButton.setBackground(new java.awt.Color(22, 16, 16));
        raiseCSRRequestButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raiseCSRRequestButtonMouseClicked(evt);
            }
        });
        raiseCSRRequestButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ngoFunctionLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        ngoFunctionLabel.setForeground(new java.awt.Color(204, 204, 204));
        ngoFunctionLabel.setText("Raise CSR Request");
        raiseCSRRequestButton.add(ngoFunctionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));
        raiseCSRRequestButton.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 0, -1, 38));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coin-stack-1.png"))); // NOI18N
        raiseCSRRequestButton.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(raiseCSRRequestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 173, 430, 56));

        manageUserAccount.setBackground(new java.awt.Color(22, 16, 16));
        manageUserAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageUserAccountMouseClicked(evt);
            }
        });
        manageUserAccount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Manage User Account");
        manageUserAccount.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 22, -1, -1));
        manageUserAccount.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 0, -1, 90));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id-card-1.png"))); // NOI18N
        manageUserAccount.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(manageUserAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 303, 430, 61));

        manageResourceButton.setBackground(new java.awt.Color(22, 16, 16));
        manageResourceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageResourceButtonMouseClicked(evt);
            }
        });
        manageResourceButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Manage Resource ");
        manageResourceButton.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));
        manageResourceButton.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, 90));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user-add.png"))); // NOI18N
        manageResourceButton.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(manageResourceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 366, 430, 64));

        viewRequestsButton.setBackground(new java.awt.Color(22, 16, 16));
        viewRequestsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewRequestsButtonMouseClicked(evt);
            }
        });
        viewRequestsButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("View open request");
        viewRequestsButton.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email-outbox.png"))); // NOI18N
        viewRequestsButton.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(viewRequestsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 437, 430, 63));

        manageEmployeeButton.setBackground(new java.awt.Color(22, 16, 16));
        manageEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageEmployeeButtonMouseClicked(evt);
            }
        });
        manageEmployeeButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Manage Organization and Employee");
        manageEmployeeButton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));
        manageEmployeeButton.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, 90));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/building-6.png"))); // NOI18N
        manageEmployeeButton.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(manageEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, 430, 60));

        manageReport.setBackground(new java.awt.Color(22, 16, 16));
        manageReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageReportMouseClicked(evt);
            }
        });
        manageReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(204, 204, 204));
        jLabel47.setText("Manage Reports");
        manageReport.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file-notes-document.png"))); // NOI18N
        manageReport.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 40, 30));

        jPanel4.add(manageReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 507, 430, 63));

        logoutJButton.setBackground(new java.awt.Color(22, 16, 16));
        logoutJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutJButtonMouseClicked(evt);
            }
        });
        logoutJButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(204, 204, 204));
        jLabel56.setText("Logout");
        logoutJButton.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 199, -1));
        logoutJButton.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 23, 39, -1));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lock-unlock-1.png"))); // NOI18N
        logoutJButton.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 30));

        jPanel4.add(logoutJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 647, 430, -1));

        viewResourceRequestsButton.setBackground(new java.awt.Color(22, 16, 16));
        viewResourceRequestsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewResourceRequestsButtonMouseClicked(evt);
            }
        });
        viewResourceRequestsButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("View Resource requests");
        viewResourceRequestsButton.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email-outbox.png"))); // NOI18N
        viewResourceRequestsButton.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 30));

        jPanel4.add(viewResourceRequestsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 577, 406, 63));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 990));
    }// </editor-fold>//GEN-END:initComponents

    private void moneyTextFieldjTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyTextFieldjTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyTextFieldjTextField8ActionPerformed

    private void projectDateTextFieldjTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectDateTextFieldjTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectDateTextFieldjTextField8ActionPerformed

    private void startFundRaiserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startFundRaiserMouseClicked
        FundRaisingActivityWorkRequest activityWorkRequest = new FundRaisingActivityWorkRequest();

        //ResourcesWorkRequest workRequest = new ResourcesWorkRequest();
        activityWorkRequest.setRequsetId(Integer.parseInt(requestIdTextField.getText()));
        activityWorkRequest.setMessage(descriptionTextField.getText());
        //activityWorkRequest.setNumberOfVolunteersRequired(Integer.parseInt(numberOfVolunteersTextField.getText()));
        activityWorkRequest.setMoneyNeeded(Integer.parseInt(moneyTextField.getText()));
        activityWorkRequest.setSender(system.getCurrentUserAccount());
        activityWorkRequest.setRequestDate(UtitlityMethods.getDateFromString(projectDateTextField.getText()));
        activityWorkRequest.setStatus("Pending");
        //activityWorkRequest.setEnterpriseName(enterprise.getName());
        for (Network network : system.getNetworkList()) {
            if (network.getEnterpriseDirectory().getEnterpriseList().contains(enterprise)) {
                network.getWorkQueue().getWorkRequestList().add(activityWorkRequest);
            }
        }

        JOptionPane.showMessageDialog(null, "Fund Raiser Created Successfully");
        buttonDashboardMouseClicked(null);
    }//GEN-LAST:event_startFundRaiserMouseClicked

    private void backJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backJButtonMouseClicked
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonMouseClicked

    private void buttonDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDashboardMouseClicked
        AdminWorkAreaJPanel systemAdminWorkAreaJPanel = new AdminWorkAreaJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("systemAdminWorkAreaJPanel", systemAdminWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_buttonDashboardMouseClicked

    private void raiseCSRRequestButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raiseCSRRequestButtonMouseClicked
        if (enterprise.getEnterpriseType().equals(NGOEnterprise.EnterpriseType.NGO)) {
            StartFundRaiser startFundRaiser = new StartFundRaiser(userProcessContainer, enterprise, system);
            userProcessContainer.add("startFundRaiser", startFundRaiser);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
            RaiseCSRActivityJPanel raiseCsrActivityJPanel = new RaiseCSRActivityJPanel(userProcessContainer, enterprise, system);
            userProcessContainer.add("raiseCsrActivityJPanel", raiseCsrActivityJPanel);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_raiseCSRRequestButtonMouseClicked

    private void manageUserAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserAccountMouseClicked
        ManageUserAccountJPanel manageUserAccountJPanel = new ManageUserAccountJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("manageUserAccountJPanel", manageUserAccountJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageUserAccountMouseClicked

    private void manageResourceButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageResourceButtonMouseClicked
        ManageResourcesJPanel manageResourcesJPanel = new ManageResourcesJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("manageResourcesJPanel", manageResourcesJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageResourceButtonMouseClicked

    private void viewRequestsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRequestsButtonMouseClicked
        if (enterprise.getEnterpriseType().equals(NGOEnterprise.EnterpriseType.NGO)) {
            ViewFundRaiserRequestsJPanel viewRequestsJPanel = new ViewFundRaiserRequestsJPanel(userProcessContainer, enterprise, system);
            userProcessContainer.add("viewRequestsJPanel", viewRequestsJPanel);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
            ViewCSRRequestsJPanel viewRequestsJPanel = new ViewCSRRequestsJPanel(userProcessContainer, enterprise, system);
            userProcessContainer.add("viewRequestsJPanel", viewRequestsJPanel);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_viewRequestsButtonMouseClicked

    private void manageEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEmployeeButtonMouseClicked
        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEmployeeButtonMouseClicked

    private void manageReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageReportMouseClicked
        // TODO add your handling code here:
        ManageReports manageReports = new ManageReports(userProcessContainer, enterprise, system);
        userProcessContainer.add("manageReports", manageReports);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageReportMouseClicked

    private void logoutJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutJButtonMouseClicked
        userProcessContainer.removeAll();
        dB4OUtil.storeSystem(system);
        MainPanel mainJPanel = new MainPanel();
        userProcessContainer.add("mainJPanel", mainJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_logoutJButtonMouseClicked

    private void viewResourceRequestsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewResourceRequestsButtonMouseClicked

        ViewOpenResourceRequestsJPanel viewOpenResourceRequestsJPanel = new ViewOpenResourceRequestsJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("viewOpenResourceRequestsJPanel", viewOpenResourceRequestsJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewResourceRequestsButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backJButton;
    private javax.swing.JPanel buttonDashboard;
    private javax.swing.JTextArea descriptionTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel logoutJButton;
    private javax.swing.JPanel manageEmployeeButton;
    private javax.swing.JPanel manageReport;
    private javax.swing.JPanel manageResourceButton;
    private javax.swing.JPanel manageUserAccount;
    private javax.swing.JTextField moneyTextField;
    private javax.swing.JLabel ngoFunctionLabel;
    private javax.swing.JTextField projectDateTextField;
    private javax.swing.JPanel raiseCSRRequestButton;
    private javax.swing.JTextField requestIdTextField;
    private javax.swing.JPanel startFundRaiser;
    private javax.swing.JPanel viewRequestsButton;
    private javax.swing.JPanel viewResourceRequestsButton;
    private javax.swing.JLabel windowLabel;
    // End of variables declaration//GEN-END:variables
}
